### PR TITLE
Refactoring to add up SW section

### PR DESCRIPTION
**Pull request by pattacini**
This PR introduces the summary page where to collect SW info.

### CODE REVIEW

**Comment by traversaro** [comment]
The section https://icub-tech-iit.github.io/documentation/icub_starter_kits/first_steps/ does not seem to be strictly related to HW.

**Comment by pattacini** [comment]
Yep 👍🏻
I think we can move it up to the home page, what do you think?

**Comment by pattacini** [comment]
I'm gonna do that.

**Comment by traversaro** [comment]
> 
> 
> Yep 👍🏻
> I think we can move it up to the home page, what do you think?

I totally agree, being an entry point for new iCub users. I guess that @violadelbono can also provide useful input on this as I think she is the one that wrote that docs.

**Comment by pattacini** [comment]
Looks quite good:

image

**Comment by violadelbono** [comment]
I agree, it makes more sense!

**Pull request merged**
