### PR TITLE
updated documentation for fingertips mk.2

### PR DESCRIPTION
**Pull request by simeonedussoni**
as per user request, I have:
- corrected the IITCODEs of the used electronics
- unified ergocub SN0001 to the following since it is equipped with the same transition board
- applied some minor refinemenents

### CODE REVIEW

**Comment by simeonedussoni** [comment]
I'm testing the workflow. I'll let know when ready.

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @simeonedussoni 

We cannot post in public repos links to private repos.
Therefore, would you mind making the OP explicit?

**Comment by simeonedussoni** [comment]
seems that the gh-pages bot has succesfully rendered the documentation page.

switching to `ready for review`

**Review by pattacini — APPROVED** [review]
Thanks!

**Pull request merged**
