### PR TITLE
Hand_MK5: add coupling law documentation

### PR DESCRIPTION
**Pull request by Nicogene**
This has been written converting the existing documentation from docx to markdown.

cc @traversaro @ale-git @fiorisi @Xenvre

### CODE REVIEW

**Review by pattacini — CHANGES_REQUESTED** [review]
Just a few preliminary comments to begin with:
- We'd need to update https://icub-tech-iit.github.io/documentation/hands.
- We also need to extend the main navigation pane in `mkdocs.yml`.

**Comment by pattacini** [comment]
Sorry, I overlooked the point. 
Better off dedicating a file for the coupling instead of filling in the main one.
Then, we need to update the main resources pointing to the new file.

**Comment by Nicogene** [comment]
> Sorry, I overlooked the point.
Better off dedicating a file for the coupling instead of filling in the main one.
Then, we need to update the main resources pointing to the new file.

Done

**Review by pattacini — COMMENTED** [review]
Nice, thanks!

The page is rendered like this for what concerns the images:

image

Perhaps, we can increase the resolution so that the variables are more visible?

What do you think @Nicogene?

**Comment by pattacini** [comment]
I'm merging the PR anyway.
Later, I'll increase the resolution of those images.

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
>Later, I'll increase the resolution of those images.

Actually, the [final rendering](https://icub-tech-iit.github.io/documentation/hands/hands_mk5_coupling/) is sufficient!

**Pull request merged**
