### PR TITLE
Fix FT-IMU frames conversion

### PR DESCRIPTION
**Pull request by pattacini**
This PR fixes a problem we spotted in the conversion between the FT reference frame and the frame of the mounted IMU.

cc @davidetome @simeonedussoni

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @isorrentino

**Comment by traversaro** [comment]
The idea is to release this fix with icub-firmware v1.26.0 / distro v2022.08, right?

**Comment by pattacini** [comment]
The PR has already landed on the FW, so it depends on @marcoaccame when he wants to release the fix.
We could also think of targeting the upcoming Distro 2022.05.1, if needed.

**Comment by traversaro** [comment]
That would be great, but are you ok on shipping in 2022.05.1 (or actually 2022.05.2, 2022.05.1 was released yesterday : ) ) also the other changes that were committed to icub-firmware devel in the meantime, i.e. : 
* https://github.com/robotology/icub-firmware/pull/271
* https://github.com/robotology/icub-firmware/pull/269

**Comment by pattacini** [comment]
The 2 changes you spotted are fine as they pertain to AMC and AMCBLDC development, I suppose.
So, first, we need the green light from @marcoaccame.
In the case of 🟢, we should coordinate w/ you and @Nicogene for the correct deliveries.

**Pull request merged**
