### PR TITLE
added dedicated page for BT

### PR DESCRIPTION
**Pull request by mbrunettini**

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @mbrunettini 
Tests are failing.
Could you fix this

>WARNING -  A relative path to 'icub_operating_systems/icubos/bluetooth.md' is included in the 'nav' configuration, which is not found in the documentation files

**Comment by mbrunettini** [comment]
@pattacini : I have the fix on my branch: now what's the correct workflow? removing this PR an creating a new one?

**Comment by pattacini** [comment]
>@pattacini : I have the fix on my branch: now what's the correct workflow? removing this PR an creating a new one?

Just push to your branch/fork and the PR will get magically updated 👍🏻

**Comment by pattacini** [comment]
I've seen now the fix! Great!

**Comment by mbrunettini** [comment]
@pattacini : you are far too quick! 🚀

**Pull request merged**
