### PR TITLE
documentation about MMA connection scheme and hand sensorization

### PR DESCRIPTION
**Pull request by simeonedussoni**
documentation updated with the info about
- electronics board: FT3D and FAP5
- passive connector board: the MMA
- cabling

### CODE REVIEW

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @simeonedussoni 

The [CI failed](https://github.com/icub-tech-iit/documentation/actions/runs/3893780340/jobs/6646845842) with the following errors:
```console
ERROR    -  Encoding error reading file: hands/fingertip_and_mma_mk5.md
ERROR    -  Error reading page 'hands/fingertip_and_mma_mk5.md': 'utf-8' codec can't decode byte 0xef in position [35](https://github.com/icub-tech-iit/documentation/actions/runs/3893780340/jobs/6646845842#step:5:36)03: invalid continuation byte
Traceback (most recent call last):
  File "/home/runner/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1[39](https://github.com/icub-tech-iit/documentation/actions/runs/3893780340/jobs/6646845842#step:5:40)5, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 2[50](https://github.com/icub-tech-iit/documentation/actions/runs/3893780340/jobs/6646845842#step:5:51), in build_command
    build.build(cfg, dirty=not clean)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.read_source(config)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 217, in read_source
    source = f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.10/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 3503: invalid continuation byte
```

There must be a character error in that file.

Could you have a look at it?

Pushing to your `master` is sufficient to upload the fix.

**Review by pattacini — APPROVED** [review]
Hi @simeonedussoni 

I've gone with a few minor "cosmetic" modifications but I'm unable to push to your fork. Can you please grant me the rights?

**Comment by simeonedussoni** [comment]
hi @pattacini, you should have writing rights.

**Comment by pattacini** [comment]
> hi @pattacini, you should have writing rights.

Yep, accepted, thanks!

However, I still get the following error while pushing:
```console
gitpod@simeoneduss-documentati-ve8cx3gyku0:/workspace/documentation$ git push
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 16 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 172.98 KiB | 15.72 MiB/s, done.
Total 8 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access. Commits must have valid signatures.
To https://github.com/simeonedussoni/documentation.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/simeonedussoni/documentation.git'
```

I'll come to you to check the configuration of your master branch.

**Comment by pattacini** [comment]
@simeonedussoni, we should check this on your settings:

https://stackoverflow.com/a/62933851/3956237

**Comment by pattacini** [comment]
Done! My amendments are in 619c9d1d613b56d1ee3b3c5fe32b987b86be54e7.

**Comment by pattacini** [comment]
I've also reduced the size of a couple of images.

**Pull request merged**
