### PR TITLE
fixed with next release of iCubServerOS

### PR DESCRIPTION
**Pull request by mbrunettini**

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @mbrunettini 

GH notified us that we have conflicts on `docs/icub_operating_systems/other-machines/icub-server-from-scratch.md`.

Can you sort it out?

**Comment by pattacini** [comment]
Rebasing `mbrunettini@master` on `icub-tech-iit@master` should do the job.

**Review by pattacini — APPROVED** [review]
I've solved it using the GH dashboard.
Was just a very tiny formatting difference.

**Comment by mbrunettini** [comment]
Thanks @pattacini, yesterday I had no time to fix it up, sorry

**Pull request merged**
